version: '3.8'

services:
  zookeeper:
    image: 'zookeeper:3.8'
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:7.4.0'
    container_name: kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  postgres:
    image: 'postgres:15'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crime_db
    volumes:
      - ../db/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: 'mongo:6'
    container_name: mongo
    ports:
      - '27017:27017'

  spark:
    image: 'apache/spark-py:latest'
    container_name: spark
    user: root
    volumes:
      - ../data:/data
      - ../spark:/opt/spark-apps
    command: bash -c "pip install numpy && tail -f /dev/null"
  nimbus:
    build:
      context: ..
      dockerfile: docker/Dockerfile.storm
    container_name: nimbus
    environment:
      - IN_DOCKER=1
    command: storm nimbus
    depends_on:
      - zookeeper
    ports:
      - '6627:6627'
    volumes:
      - ../storm:/app/storm
      - ../config:/app/config

  supervisor:
    build:
      context: ..
      dockerfile: docker/Dockerfile.storm
    container_name: supervisor
    environment:
      - IN_DOCKER=1
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    volumes:
      - ../storm:/app/storm
      - ../config:/app/config

  storm-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.storm
    container_name: storm-ui
    command: storm ui
    depends_on:
      - nimbus
    ports:
      - '8081:8080'

  # A python runner container that mounts our local directory to run scripts easily
  runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: runner
    volumes:
      - ../:/app
    tty: true
    ports:
      - '8501:8501'
    depends_on:
      - kafka
      - postgres
      - mongo
